<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>     
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <LangVersion>12</LangVersion>
	<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>
  <PropertyGroup>    
    <OutputType>Library</OutputType>
    <RootNamespace>Decisions.USPS</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>
    <RootPath>../</RootPath>  
    <BuildDest>$(RootPath)obj</BuildDest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DecisionsSDK" Version="10.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
